name: Postman-CLI-test

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  test-echo-collection:
    runs-on: ubuntu-latest
    steps:
      - name: Run Postman Collection
        uses: postmanlabs/postman-cli-action@v1
        with:
          command: 'collection run ./postman/Postman_Echo_Basis_Collection.postman_collection.json --environment ./postman/Postman_Echo_Basis_Environment.postman_environment.json'
